Fix fscanf overflow error
Fix the below fscanf overflow error:
error: 'fscanf' may overflow; destination buffer in argument 4
has size 24, but the corresponding specifier may require size
25 [-Werror,-Wfortify-source]
  fscanf(to, "#V1.0 %16s%24s\n", name, lastbootuptime);

Tracked-On: OAM-103588
Signed-off-by: svenate <salini.venate@intel.com>